Add test case for rename file
redhat-developer/vscode-java pull request #1574
Opened 2020-08-12 08:13 UTC by jdneo

This is to prevent the regression in the future, for the issue: #1517

Signed-off-by: Sheng Chen <sheche@microsoft.com>

2020-08-21 01:49 UTC, testforstephen commented on test/standard-mode-suite/rename.test.ts
> +		await workspace.applyEdit(workspaceEdit);
The unit test will modify the test project file in the source code directly. Can you copy it to some temporary directory and modify there?

2020-08-24 08:27 UTC, fbricon requested changes
Change the test so that it doesn't mutate the sources

2020-08-24 08:32 UTC, jdneo commented on test/standard-mode-suite/rename.test.ts
> +		await workspace.applyEdit(workspaceEdit);
ok

2020-08-25 03:14 UTC, jdneo commented
@fbricon Would you mind to tag this PR to a later milestone? I need sometime to figure out if there is some elegant way to prepare the test folder and launch the tests. (Launch from `npm run test` and VS Code launch configuration have different entrances).

2020-08-27 04:38 UTC, jdneo commented
Updated

2020-08-28 09:09 UTC, merged

2020-08-28 09:10 UTC, fbricon commented
Thanks @jdneo!