Surround with try/catch reformats document
redhat-developer/vscode-java pull request #1631
Opened 2020-09-21 18:31 UTC by snjeza

Fixes #1572 
Requires https://github.com/eclipse/eclipse.jdt.ls/pull/1551

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

2020-09-22 13:19 UTC, fbricon requested changes

2020-09-22 13:19 UTC, fbricon commented on package.json
> +        },
I don't think it makes sense to expose new  tab settings to users, it'll be more confusing than anything. Why would anyone want to use different tab settings than the ones from vscode?

2020-09-22 13:19 UTC, fbricon commented on README.md
> +
No need to expose those settings

2020-09-22 13:19 UTC, fbricon commented on src/extension.ts
> +		javaConfig.editor.insertSpaces = editorConfig.get('insertSpaces');
javaConfig.format.insertSpaces

2020-09-22 13:19 UTC, fbricon commented on src/extension.ts
> +		javaConfig.editor.tabSize = editorConfig.get('tabSize');
javaConfig.format.tabSize

2020-09-22 19:28 UTC, snjeza commented on README.md
> +
Fixed

2020-09-22 19:28 UTC, snjeza commented on package.json
> +        },
Fixed.

2020-09-22 19:28 UTC, snjeza commented on src/extension.ts
> +		javaConfig.editor.tabSize = editorConfig.get('tabSize');
Fixed

2020-09-22 19:29 UTC, snjeza commented on src/extension.ts
> +		javaConfig.editor.insertSpaces = editorConfig.get('insertSpaces');
Fixed

2020-09-25 16:37 UTC, fbricon commented
unfortunately, if vscode's default setting is set to use spaces/4, but the document contains only tab/4, then adding new lines manually will have vscode automatically detect the indentation and insert tabs, but applying a code action will insert spaces.
That's the one good thing the previous code had, i.e. maintain consistent editing experience.

I think we'll need to apply https://github.com/redhat-developer/vscode-java/pull/1081/ to make it useable.

2020-09-29 17:16 UTC, snjeza commented
> I think we'll need to apply #1081 to make it useable.

Agree.

2021-02-24 02:47 UTC, testforstephen commented
There is another PR https://github.com/eclipse/eclipse.jdt.ls/pull/1657 to use #1081, so no need to take care of it in this PR.

@snjeza could you rebase and resolve the conflicts?

2021-02-24 04:30 UTC, snjeza commented
> @snjeza could you rebase and resolve the conflicts?

Done.

2021-02-24 08:44 UTC, testforstephen commented on src/extension.ts
> +	javaConfig.format.tabSize = editorConfig.get('tabSize');
You should add "editor.insertSpaces" and "editor.tabSize" to [the synchronized configuration sections](https://github.com/redhat-developer/vscode-java/blob/master/src/extension.ts#L163) as well.

![image](https://user-images.githubusercontent.com/14052197/108973373-3a11ac80-76bf-11eb-9627-d434b556b1c9.png)

2021-02-24 18:35 UTC, snjeza commented on src/extension.ts
> +	javaConfig.format.tabSize = editorConfig.get('tabSize');
Fixed.

2021-02-25 01:30 UTC, testforstephen approved these changes

2021-02-25 01:32 UTC, merged