feat: Recommend dependency analytics extension
redhat-developer/vscode-java pull request #1771
Opened 2021-01-18 13:16 UTC by arajkumar

Changes are inspired by https://github.com/microsoft/vscode-java-pack/tree/master/src/recommendation.

<img width="1792" alt="Screenshot 2021-01-18 at 6 42 43 PM" src="https://user-images.githubusercontent.com/3874763/104919884-f9868b00-59bc-11eb-9001-81741ba634ef.png">

Fixes https://github.com/redhat-developer/vscode-java/issues/1763

2021-01-25 08:53 UTC, fbricon commented on src/recommendation/dependencyAnalytics.ts
> +const RECOMMENDATION_MESSAGE = `[Dependency Analytics](${MARKETPLACE_URL}) extension is recommended to get insights about pom.xml.`;
is recommended to get security insights about pom.xml

2021-01-25 08:55 UTC, fbricon commented on src/recommendation/dependencyAnalytics.ts
> +const MARKETPLACE_URL = `https://marketplace.visualstudio.com/items?itemName=${EXTENSION_NAME}`;
I suggest we use the GitHub URL instead, since the marketplace can be either VS Code's or open-vsx (in Theia, Che, VS Codium), I don't think we have any way to know the url used by the client.

2021-01-25 09:07 UTC, arajkumar commented on src/recommendation/dependencyAnalytics.ts
> +const RECOMMENDATION_MESSAGE = `[Dependency Analytics](${MARKETPLACE_URL}) extension is recommended to get insights about pom.xml.`;
Done.

2021-01-25 09:07 UTC, arajkumar commented on src/recommendation/dependencyAnalytics.ts
> +const MARKETPLACE_URL = `https://marketplace.visualstudio.com/items?itemName=${EXTENSION_NAME}`;
Done.

2021-01-26 16:16 UTC, rgrunber requested changes
Overall, looks fine. Just had one suggestion about avoiding excessive checks in the callbacks.

I also tried this on project with a large amount of poms ( https://git.eclipse.org/c/orbit/orbit-recipes.git/tree/ ) and it hit a timeout exception :

`Failed to trigger application's stack analysis, try in a while. Status: 408 - REQUEST TIMEOUT`

The analytics page came back empty with just the text "Unable to analyze your stack." . If this is expected in more extreme cases then I guess that's fine for now.

2021-01-26 16:34 UTC, arajkumar commented on src/recommendation/dependencyAnalytics.ts
> +	context.subscriptions.push(vscode.workspace.onDidOpenTextDocument(e => {
Thanks @rgrunber for taking a look.

> Overall, looks fine. Just had one suggestion about avoiding excessive checks in the callbacks.
> 

This can be done. Let me try that.

> I also tried this on project with a large amount of poms ( https://git.eclipse.org/c/orbit/orbit-recipes.git/tree/ ) and it hit a timeout exception :
> 
> `Failed to trigger application's stack analysis, try in a while. Status: 408 - REQUEST TIMEOUT`
> 
> The analytics page came back empty with just the text "Unable to analyze your stack." . If this is expected in more extreme cases then I guess that's fine for now.

Large stacks known to timeout, we will look into the backend.

2021-01-26 16:46 UTC, arajkumar commented on src/recommendation/dependencyAnalytics.ts
> +	context.subscriptions.push(vscode.workspace.onDidOpenTextDocument(e => {
@rgrunber , Incorporated your comments. PTAL. Thanks!

2021-01-27 18:30 UTC, rgrunber commented on src/recommendation/dependencyAnalytics.ts
> +	context.subscriptions.push(vscode.workspace.onDidOpenTextDocument(e => {
Great! How about the `Never` case though ? A user selects `Never` for the analytics recommendation (and doesn't install it separately). On subsequent launches of VSCode and opening of pom files, they would still have the handler triggered only to exit. Might as well terminate early like we did for when the extension is installed.

2021-01-28 08:41 UTC, arajkumar commented on src/recommendation/dependencyAnalytics.ts
> +	context.subscriptions.push(vscode.workspace.onDidOpenTextDocument(e => {
Added check for `Never` case also. PTAL @rgrunber

2021-01-28 17:57 UTC, rgrunber approved these changes
Thanks for addressing the issues.

I've tested each case, in addition to installing/uninstalling the analytics independent of the recommendation code. It seems to be doing the right thing each time.

Can you just squash the commits into 1 and then we can merge this.

2021-01-28 17:57 UTC, rgrunber commented on src/recommendation/dependencyAnalytics.ts
> +	context.subscriptions.push(vscode.workspace.onDidOpenTextDocument(e => {
Looks good to me now.

2021-01-28 18:56 UTC, rgrunber commented
Merged as bdacd431c8c7a97d014891a1dfa279c715715473 .

2021-01-28 18:56 UTC, closed without merging

2021-01-28 19:00 UTC, arajkumar commented
> Can you just squash the commits into 1 and then we can merge this.

Usually we (in our team) prefer to do squash merge offered from Github., but I'm not sure whether it does signed commits. :)

Thanks for review this.

<img width="312" alt="Screenshot 2021-01-29 at 12 29 27 AM" src="https://user-images.githubusercontent.com/3874763/106185620-0ed39480-61c9-11eb-9063-1b0585983c19.png">