Add new contribution point that allows other extension to register the build file pattern.
redhat-developer/vscode-java pull request #1845
Opened 2021-03-24 09:17 UTC by LeonovecSergey

Add new contribution point that allows other extension to register the build file pattern.

Close https://github.com/redhat-developer/vscode-java/issues/1825

Signed-off-by: Siarhei Leanavets siarhei_leanavets1@epam.com

2021-03-25 03:10 UTC, jdneo commented
Hi @LeonovecSergey,

I have two general comments about this PR.

1. `isBuildFilePattern()` is called every time `isJavaConfigFile()` is called. At least we can cache all the available patterns to avoid iterating all the extension metadata every time.
2. The `pattern` here should be defined more clearly, from the implementation it's a `suffix`. Maybe there is more space for improvement here. VS Code uses [regular expression](https://code.visualstudio.com/api/references/when-clause-contexts#conditional-operators) for its when clause. Can we also use that for our patterns?

2021-03-31 01:54 UTC, jdneo requested changes

2021-03-31 01:54 UTC, jdneo commented on src/plugin.ts
> +	if (hasChanged) {
If both Java extension and file patterns are changed. Users will see two pop-up dialog asking for reload, which I think is a little bit annoying.

How about migrate the two function into one named something like `updateJavaExtensionContributions()`

2021-03-31 01:54 UTC, jdneo commented on src/standardLanguageClient.ts
> +	return buildFilePatterns.filter((pattern: String) => path.toLowerCase().endsWith(pattern.toLowerCase()))
Here we need to figure out the rules for this new contribution point.

1. If we call it `javaBuildFilePatterns`, we need to use a pattern mechanism to check it, for example, regular expression.
2. If we just check it via `xxx.endWith(...)`, the field should be called `javaBuildFileNames`.

Personally I prefer the first one, because it has scalability for the future. And regular expression is well used in VS Code when clause.

2021-04-05 20:43 UTC, LeonovecSergey commented on src/plugin.ts
> +	if (hasChanged) {
@jdneo done

2021-04-05 20:43 UTC, LeonovecSergey commented on src/standardLanguageClient.ts
> +	return buildFilePatterns.filter((pattern: String) => path.toLowerCase().endsWith(pattern.toLowerCase()))
@jdneo done

2021-04-06 00:50 UTC, jdneo commented on src/plugin.ts
> +let existingBuildFilePatterns: Array<string>;
I find there are two copies for the build file patterns (one here and another in src/standardLanguageClient.ts). Can we just have one? Maybe just use the one from standardLanguageClient.ts.

2021-04-07 07:22 UTC, jdneo commented on src/standardLanguageClient.ts
> +	const fileName = require("path").basename(path);
No need to use `require` here. The `path` module is already imported in this file (line 15.)

2021-04-07 07:22 UTC, jdneo commented on src/plugin.ts
> +	const hasChanged = ( oldPatterns.size !== newPatterns.length);
Just curious: what will happen when the sizes are equal but the contents are different? For example, update an extension that the build patterns registered by the extension changes.

2021-04-07 07:22 UTC, jdneo commented
Have no idea why CI fails. BTW, @LeonovecSergey do you know how we can verify this change manually?

2021-04-07 19:04 UTC, LeonovecSergey commented on src/plugin.ts
> +	const hasChanged = ( oldPatterns.size !== newPatterns.length);
For this case we have "if (!hasChanged)" where the content of the oldPatterns and the newPatterns is compared

2021-04-07 20:05 UTC, LeonovecSergey commented
> Have no idea why CI fails. BTW, @LeonovecSergey do you know how we can verify this change manually(like the steps using the Bazel extension to play around)?

I use debug breakpoints to track java extension and build file patterns changes 

1. Open vscode-java fork in VSCode
2. Launch as Extension
3. In the opened window open some maven or gradle project (e.g. https://github.com/gradle/gradle-build-scan-quickstart)
4. Update project (e.g shift+alt+U) for watching current state of java extensions and build file patterns
5. Install new VSCode Extension that will add java extension or build file patterns from contributes in package.json (You can find vsix file in attached zip document)
6. Click on the pop-up Reload button
7. Update project (e.g shift+alt+U) for watching current state of java extensions and build file patterns 
[bazel-ls-vscode-0.0.1.zip](https://github.com/redhat-developer/vscode-java/files/6274135/bazel-ls-vscode-0.0.1.zip)

2021-04-08 01:49 UTC, jdneo commented on src/plugin.ts
> +	const oldExtensions = new Set(oldContributedPart.slice());
Like the way we merge two functions into one, then I guess the variable name here should also be updated? Something like `oldContribution` `newContribution`?

2021-04-08 01:50 UTC, jdneo commented
> > Have no idea why CI fails. BTW, @LeonovecSergey do you know how we can verify this change manually(like the steps using the Bazel extension to play around)?
> 
> I use debug breakpoints to track java extension and build file patterns changes
> 
> 1. Open vscode-java fork in VSCode
> 2. Launch as Extension
> 3. In the opened window open some maven or gradle project (e.g. https://github.com/gradle/gradle-build-scan-quickstart)
> 4. Update project (e.g shift+alt+U) for watching current state of java extensions and build file patterns
> 5. Install new VSCode Extension that will add java extension or build file patterns from contributes in package.json (You can find vsix file in attached zip document)
> 6. Click on the pop-up Reload button
> 7. Update project (e.g shift+alt+U) for watching current state of java extensions and build file patterns
>    [bazel-ls-vscode-0.0.1.zip](https://github.com/redhat-developer/vscode-java/files/6274135/bazel-ls-vscode-0.0.1.zip)

Thanks for the detailed steps, will have a try!

2021-04-09 02:46 UTC, jdneo commented
It works fine, when I installed the private build, the dialog pops up to ask for reloading.

Just one more question, I used this project for testing https://github.com/bmuschko/bazel-examples/tree/master/java/junit4-test, after reload, the classpath seems still not correct(red squiggles in the code), any steps I missed?

2021-04-09 14:40 UTC, LeonovecSergey commented
> It works fine, when I installed the private build, the dialog pops up to ask for reloading.
> 
> Just one more question, I used this project for testing https://github.com/bmuschko/bazel-examples/tree/master/java/junit4-test, after reload, the classpath seems still not correct(red squiggles in the code), any steps I missed?

It is normal that the plugin did not resolve the classpath. There're two reasons for this:
1. Our plugin supports a specific project structure only
    e.g. https://github.com/salesforce/bazel-ls-demo-project/tree/master/small
   And also you need to add some settings to the setting.json file: 
   "java.import.bazel.enabled": true,
   "java.import.bazel.src.path": "/java/src",
    "java.import.bazel.test.path": "/java/test"
2. The plugin used new features of eclipse.jdt.ls, which are not currently available in the release version. 
    https://github.com/eclipse/eclipse.jdt.ls/pull/1694

2021-04-15 02:22 UTC, jdneo commented on src/plugin.ts
> +	buildFilePatterns = result.slice();
There is a potential bug here. the cache `buildFilePatterns` is updated during the collect function, then passed as the `oldContributedPart` to `isContributedPartUpdated()`, that will cause `isContributedPartUpdated()` always return false.

Same to `existingExtensions`

2021-04-17 03:01 UTC, jdneo commented
The problem fixed. It can pop-up the dialog for reloading when contribution changes.

Though I still cannot import the sample project, there is an error saying:

```
[Info  - 10:59:47 AM] Apr 17, 2021, 10:59:47 AM Tried to link a non-existant file [/Users/neo/Downloads/bazel-ls-demo-project-master/small/BUILD] for project [Bazel Workspace (small)]
[Error - 10:59:47 AM] Apr 17, 2021, 10:59:47 AM Initialization failed 
java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at com.salesforce.b2eclipse.config.BazelEclipseProjectFactory.precomputeBazelAspectsForWorkspace(BazelEclipseProjectFactory.java:601)
	at com.salesforce.b2eclipse.config.BazelEclipseProjectFactory.importWorkspace(BazelEclipseProjectFactory.java:175)
	at com.salesforce.b2eclipse.managers.BazelProjectImporter.importToWorkspace(BazelProjectImporter.java:81)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:113)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:102)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:187)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at com.salesforce.b2eclipse.config.BazelEclipseProjectFactory.precomputeBazelAspectsForWorkspace(BazelEclipseProjectFactory.java:597)
	... 7 more
```

Anyway, this is another problem beyond the scope of this PR. Overall the PR LGTM now.

+ @testforstephen @rgrunber @fbricon for awareness

2021-04-17 03:02 UTC, jdneo approved these changes

2021-04-20 08:25 UTC, merged

2021-04-20 08:25 UTC, fbricon commented
Thanks @LeonovecSergey!