Add changelog for 0.78.0
redhat-developer/vscode-java pull request #1906
Opened 2021-04-28 02:09 UTC by rgrunber

Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

2021-04-28 21:31 UTC, fbricon requested changes

2021-04-28 21:31 UTC, fbricon commented on CHANGELOG.md
> + * debt - Update Maven wrapper to use 3.8.1. See [JLS#1734](https://github.com/eclipse/eclipse.jdt.ls/pull/1734).
irrelevant here

2021-04-28 21:31 UTC, fbricon commented on CHANGELOG.md
> + * other - Engineering: Tune the project settings. See [JLS#1737](https://github.com/eclipse/eclipse.jdt.ls/pull/1737).
irrelevant

2021-04-28 21:31 UTC, fbricon commented on CHANGELOG.md
> + * enhancement - How can I add bazel support?. See [#1825](https://github.com/redhat-developer/vscode-java/issues/1825).
provide support for 3rd party build types (Bazel)

2021-04-29 03:04 UTC, testforstephen commented on CHANGELOG.md
> + * enhancement - Adopt resolveCodeAction capability. See [JLS#1606](https://github.com/eclipse/eclipse.jdt.ls/issues/1606).
Without language client 7.0, vscode-java won't enable resolveCodeAction capability. I prefer to defer the announcement for this enhancement in 0.79.0 since you mentioned we're going to merge language client 7.0 in 0.79.0 release.

2021-04-29 03:06 UTC, testforstephen commented on CHANGELOG.md
> + * enhancement - Adopt resolveCodeAction capability. See [JLS#1606](https://github.com/eclipse/eclipse.jdt.ls/issues/1606).
The changelog in eclipse.jdt.ls side is OK, because it's client neutral.

2021-04-29 03:19 UTC, rgrunber commented on CHANGELOG.md
> + * enhancement - Adopt resolveCodeAction capability. See [JLS#1606](https://github.com/eclipse/eclipse.jdt.ls/issues/1606).
Ok, I'll leave this out since it's not enabled for now.

2021-04-29 03:29 UTC, testforstephen approved these changes

2021-04-29 03:36 UTC, merged