Provide fix suggestions for not covered Maven plugin execution in project build lifecycle
redhat-developer/vscode-java pull request #1949
Opened 2021-05-17 07:08 UTC by testforstephen

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

This PR requires the side PR at https://github.com/eclipse/eclipse.jdt.ls/pull/1770. It's used to mitigate the issues at https://github.com/redhat-developer/vscode-java/issues/177, https://github.com/redhat-developer/vscode-java/issues/566, https://github.com/redhat-developer/vscode-java/issues/935 and https://github.com/redhat-developer/vscode-java/issues/1910.

Here are the main things this PR added.
- Change the default value of preference "java.configuration.maven.notCoveredPluginExecutionSeverity" to "error", and show error diagnostics to user for awareness.
- Provide quickfix suggestions for not covered Maven plugin execution in pom.xml.

2021-05-17 07:33 UTC, testforstephen commented
See a sample project https://github.com/antlr/stringtemplate4 to try this PR.
See a demo about the UX.

https://user-images.githubusercontent.com/14052197/118446113-d3ca8200-b721-11eb-8738-b11f6afe7f8c.mov

A follow-up improvement is to "discover new m2e connectors". Eclipse provides such a quick fix when reporting "not covered execution" error in Maven project. Looks like it's based on the catalog https://repo1.maven.org/maven2/.m2e/discovery-catalog/connectors.xml for discovery. Need more evaluation on the cost to support discovering and installing m2e connector, will take it as a future improvement.

// @fbricon Could you help review the solution? thanks.

2021-05-18 09:38 UTC, fbricon requested changes
I guess it will help in some cases, but I'm afraid we're opening a can of worms with the whole m2e connector thing (especially the discovery mechanism).

The best thing is still for maven plugins authors to provide [native support for m2e](https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html). The doc should probably encourage users to request such integration directly from these projects.

2021-05-18 09:38 UTC, fbricon commented on document/_java.notCoveredExecution.md
> +- Option 1: Use [build-helper-maven-plugin](http://www.mojohaus.org/build-helper-maven-plugin/usage.html) to explicitly add the unrecoginzed source folder to classpath.
unrecognized

2021-05-19 08:40 UTC, testforstephen commented
Yes, the m2e connectors are a bit too complex and not planned to add them to VS Code. We are currently just providing some suggestions for common workarounds, and also stating in the doc that the best approach would be to make the Maven plugin directly compatible with m2e.

2021-05-31 07:39 UTC, testforstephen commented
Update: 
- The latest commit has changed the default severity level to "warning".
- The PI didn't break the deployment to maven central.
Tried deploying a pom with PI `<?m2e execute onConfiguration?>` to oss.sonatype.org, it worked. And reference the sample dependency in other maven project, no issues were found.

2021-06-22 13:21 UTC, rgrunber commented
I will look at this today.

2021-06-22 20:38 UTC, rgrunber requested changes
Seems to be working well. Just a few corner cases to consider.

2021-06-22 20:38 UTC, rgrunber commented on package.json
> +    "onCommand:_java.notCoveredExecution"
Is there a reason to add this ? From what I can tell, the command is only registered when the language server is activated.

2021-06-23 04:39 UTC, testforstephen commented on src/pom/pomCodeActionProvider.ts
> +				action1.edit.insert(document.uri, new Position(diagnostic.range.end.line, diagnostic.range.end.character + 1),
Nice catch. Fixed.

2021-06-23 04:40 UTC, testforstephen commented on src/pom/pomCodeActionProvider.ts
> +		const tabSize = currentTextIndentation.length / 5;
yes, using the tabSize from the active editor is more convenient.

2021-06-23 04:41 UTC, testforstephen commented on package.json
> +    "onCommand:_java.notCoveredExecution"
The quick fix is the only entry to open this document. Yes, no need to add it here.

2021-06-23 16:32 UTC, rgrunber approved these changes
LGTM. Feel free to merge when ready. I would probably squash the commits first.

2021-06-24 01:19 UTC, merged