Support platform specific extension
redhat-developer/vscode-java pull request #2183
Opened 2021-10-27 09:09 UTC by testforstephen

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

This will address the issue https://github.com/redhat-developer/vscode-java/issues/2109

Below are the tasks added by PR:
- [x] Add a gulp task to download a platform specific JRE.
      The full version is `npx gulp download_jre --target darwin-x64 --javaVersion 17`.
      The short version is `npx gulp download_jre`, which will download latest JRE for your dev machine platform.

   This task will download and decompress the artifact to a jre folder under root directory of vscode-java.
![image](https://user-images.githubusercontent.com/14052197/139040076-ddaed72c-3080-4d26-abcd-0cd1ad743c8b.png)

- [x] Adjust the JDK search logic in Java extension to allow using embedded JRE to launch Java extension itself.
      **1)** We plan to embed `org.eclipse.justj.openjdk.hotspot.jre.full.stripped-17` instead of `org.eclipse.justj.openjdk.hotspot.jre.minimal.stripped-17`. The minimal stripped is about 30M, and the full jre stripped is about 55M (only plus 25M). But the full jre stripped includes a full set of Java modules, and can cover maven project import better.
https://download.eclipse.org/justj/jres/17/downloads/latest/

    **2)** For platform extensions, we will always use the embedded JRE to launch Java extension. "java.home" setting is useless and may cause confusion, we will mark it as deprecated. And it can only be used for universal versions without embedded JRE.

    **3)** For platform extensions, it will still detect the installed JDKs in local machine. If no one was found, then pop up to install a JDK to compile users' project. The difference is we don't limit the JDK version any more. The concern is because the embedded JRE doesn't include JDK source, GTD cannot find source. To avoid confusion later, we can ask the user to install a project JDK when starting the Java extension.

- [x] Update CI job (Jenkinsfile) to allow publishing platform specific extension to VS Code marketplace.
       Since JustJ only provides 5 JRE platforms, we're going to support embedded JRE for these platforms. For other platforms, we publish a universal one without embedded JRE.
        
  Below are the CI artifacts, it includes a generic version for not supported platforms, 5 platform specific versions.
![image](https://user-images.githubusercontent.com/14052197/140313777-fe0eea2d-cead-4a4d-9f39-3d86c5984de5.png)

2021-11-04 13:22 UTC, testforstephen commented on src/requirements.ts
> +    let toolingJre: string = await findEmbeddedJRE(context);
@Eskibear for the latest JDK requirement change in vscode-java. pls check if vscode-java-pack need update as well.

2021-11-05 02:16 UTC, Eskibear commented on src/requirements.ts
> +    let toolingJre: string = await findEmbeddedJRE(context);
sure

2021-12-01 22:29 UTC, rgrunber commented on package.json
> +    "vscode": "^1.61.0"
Yup. I was expecting this to be an issue in case Theia checked the engine version and rejected based on that, but it seems to be working, so we should be good.

2021-12-03 22:26 UTC, rgrunber requested changes
Overall, works well for me.

- Under the Optional section of "Server Side Setup" in CONTRIBUTING.md, I think we should mention that a JRE can be embedded into the extension. I guess it could even go under the "Client Side Setup".

Just mentioning `npx gulp download_jre` will build a platform specific JRE but that it has options `target` and `javaVersion`, is probably enough.

- I found it useful to add something like this for debugging :

```diff
diff --git a/.vscode/launch.json b/.vscode/launch.json
index 2620f81..f502215 100644
--- a/.vscode/launch.json
+++ b/.vscode/launch.json
@@ -110,6 +110,26 @@
                        "outFiles": ["${workspaceRoot}/out/**/*.js"],
                        "preLaunchTask": "prepareLightweightTest",
                        "postDebugTask": "cleanTestFolder"
+               },
+               {
+                       "args": [
+                               "${input:gulpTask}"
+                       ],
+                       "name": "Launch Gulp Task",
+                       "program": "${workspaceFolder}/node_modules/gulp/bin/gulp.js",
+                       "request": "launch",
+                       "skipFiles": [
+                               "<node_internals>/**"
+                       ],
+                       "type": "pwa-node"
                }
-       ]
+       ],
+       "inputs": [
+        {
+            "id": "gulpTask",
+            "type":"promptString",
+            "description": "Name of the Gulp task to execute",
+            "default": "download_jre"
+        }
+    ]
 }
```

2021-12-03 22:26 UTC, rgrunber commented on src/requirements.ts
> +        }
Is there ever a case where the path is `./jre/bin/java` . Looking at the packaging logic in download_jre of the gulpfile.js, the archive is extracted into `'./jre/' + jreVersionLabel` and `jreVersionLabel` is either the version-platform-arch or the name of the file.

2021-12-06 02:40 UTC, testforstephen commented on src/requirements.ts
> +        }
No, the gulp task always decompresses the embedded jre to `'./jre/' + jreVersionLabel`. I will remove the unused condition branch.

2021-12-06 07:19 UTC, testforstephen commented on gulpfile.js
> +		if (value.startsWith("<!DOCTYPE html>")) {
The lib `gulp-download` we use doesn't expose http response status to the callback, so I will use `request` lib to get justj.manifest, which supports error status check.

2021-12-06 09:50 UTC, testforstephen commented
> Under the Optional section of "Server Side Setup" in CONTRIBUTING.md, I think we should mention that a JRE can be embedded into the extension. I guess it could even go under the "Client Side Setup".
Just mentioning `npx gulp download_jre` will build a platform specific JRE but that it has options target and javaVersion, is probably enough.

I mentioned `npx gulp download_jre` under the part "Client Side Setup", since the embedded JRE is the client related stuff.

> I found it useful to add something like this for debugging :

Nice suggestion 👍

2021-12-07 00:23 UTC, rgrunber approved these changes
Change looks good to me. Just a storage consideration and I think we're ready to merge.

2021-12-07 00:23 UTC, rgrunber commented on Jenkinsfile
> +		sh "rsync -Pzrlt --rsh=ssh --protocol=28 ${artifact.path} ${UPLOAD_LOCATION}/jdt.ls/staging"
@fbricon we currently place the vsix files under https://download.jboss.org/jbosstools/jdt.ls/staging/ & https://download.jboss.org/jbosstools/static/jdt.ls/stable/ . Do we want to create a separate directory for each version ? Any requirements to to clean staging in the future given how much faster it'll grow in size ?

2021-12-09 13:39 UTC, testforstephen commented on Jenkinsfile
> +		sh "rsync -Pzrlt --rsh=ssh --protocol=28 ${artifact.path} ${UPLOAD_LOCATION}/jdt.ls/staging"
The platform extensions uploaded to staging will be placed at a folder like "*/jdt.ls/staging/java-1.2.0-<BUILD_NUMBER>".

The artifacts uploaded to stable will be placed at a folder like "*/jdt.ls/stable/java-1.2.0".

2021-12-10 05:16 UTC, merged