Fix issue #2319: Open Java extension log doesn't open latest file
redhat-developer/vscode-java pull request #2323
Opened 2022-02-17 01:05 UTC by quanzhuo

2022-02-17 03:05 UTC, quanzhuo commented
Fixes #2319

2022-02-17 03:07 UTC, quanzhuo commented
@rgrunber Could you help to review this ?

2022-02-17 20:32 UTC, rgrunber requested changes
It definitely works, but would you be able to rewrite this in terms of overriding the `sort` function ? eg.

```
files.sort((a, b) => {
...
sorting logic here
...
}
```

I just think it's a bit simpler to read because you only need to compare 2 values (the date if not the same, and the extension number for identical dates). If it becomes too annoying I'm happy to just review this approach also.

2022-02-18 01:44 UTC, quanzhuo commented
> It definitely works, but would you be able to rewrite this in terms of overriding the `sort` function ? eg.
> 
> ```
> files.sort((a, b) => {
> ...
> sorting logic here
> ...
> }
> ```
> 
> I just think it's a bit simpler to read because you only need to compare 2 values (the date if not the same, and the extension number for identical dates). If it becomes too annoying I'm happy to just review this approach also.

Thanks for your advise. I have changed the logic, it looks better now. @rgrunber

2022-02-18 05:50 UTC, quanzhuo commented on src/extension.ts
> +					if (date1 < date2) {
> How about
> 
> ```js
> if (data1 === date2) {
>     ...
> } else {
>     return date1 - date2;
> }
> ```
> 
> You can directly return `a - b` or `b - a` in sort comparator to make the code simple.

Thank for advise, but I am not quite clear about your idea. `date1` and `date2` are strings like `2022-01-18` .  Can I apply `-` between strings? @jdneo

2022-02-18 06:37 UTC, jdneo commented on src/extension.ts
> +					if (date1 < date2) {
You could use `new Date(a) - new Date(b)`. But that will lose some performance: https://jsben.ch/Ip2Nf.

At least line 737 and line 739 could be updated.

2022-02-19 01:21 UTC, quanzhuo commented on src/extension.ts
> +					if (date1 < date2) {
line 737 and 739 updated @jdneo

2022-02-19 18:03 UTC, rgrunber commented
Change looks good to me. Just 2 minor things  :
- Instead of `date1`, `date2`, `ext1`, `ext2`, I would go with `dateA`, `dateB`, `extA`, `extB` to connect those values to their respective parameters (`a` & `b`).
- You could combine `date1 < date2` and the `else` case into 1 statement by restructuring as follows :
```
if (date1 === date2) {
  ... stays the same ...
} else {
  return date1 < date2 ? -1 : 1;
}
```

I'll leave it to @jdneo to confirm he has no other comments, but once the above is addressed, I think we can merge.

2022-02-19 22:24 UTC, quanzhuo commented
All have updated as you suggested.  Your suggestions really helps. @rgrunber @jdneo

2022-02-20 11:17 UTC, jdneo approved these changes
LGTM 👍

2022-02-21 04:43 UTC, rgrunber approved these changes

2022-02-21 05:13 UTC, merged