Show server status via language status item
redhat-developer/vscode-java pull request #2363
Opened 2022-03-16 11:49 UTC by CsCherrYY

fix #2351 

We can use language status item to show the server's status. Once the language status API is available (the check is for the compatibility with Theia), we will show the new language status item, instead of previously runtime status (language level) and server status (thumb).

## when service is ready:
![image](https://user-images.githubusercontent.com/45906942/158581892-7e7c54e6-fb39-4369-8b99-26b054eac077.png)

we will show serval statuses. 

- The first one is build file status. If the current project is an invisible project this item will disappear. The related command can help you to open the corresponding build file
- The second one is runtime status, similar with previously runtime status
- The third one is server status, similar with previously server status

We can choose to pin these statuses:
![image](https://user-images.githubusercontent.com/45906942/158582569-889a9e52-293b-4739-b141-438a3abb578e.png)

clicking the item will trigger its command as well.
## when running in lightweight mode:
![image](https://user-images.githubusercontent.com/45906942/158582781-80da9128-af55-4614-aa0a-ef84e9e90124.png)

we will show a server status telling the current lightweight mode.

We can choose to pin the status:
![image](https://user-images.githubusercontent.com/45906942/158583055-ab5813d7-a820-47a1-8b69-9e351db002e4.png)

## when there is error (`ServerStatusKind.Error` and `ServerStatusKind.Warning`, previously thumb down)

![image](https://user-images.githubusercontent.com/45906942/158583386-88d54467-91a1-4d79-90da-e2a3631879ed.png)

Compared with the first one, we will show one more item to help you clean the language server workspace.

after pinned:
![image](https://user-images.githubusercontent.com/45906942/158583647-a1563267-b617-4f92-94d3-84ed391ece01.png)

2022-03-29 06:51 UTC, testforstephen commented on src/standardLanguageClient.ts
> +				cleanWorkspaceStatusItemProvider.hide();
clean workspace is part of server status, I'd move it to serverStatusBarProvider.

2022-03-29 06:53 UTC, testforstephen commented on src/runtimeStatusBarProvider.ts
> +		this.buildFileStatusItem.command = {
lots of duplicated code are used to build a language status item, can you refactor it to a helper method?

2022-03-29 06:57 UTC, testforstephen commented on src/runtimeStatusBarProvider.ts
> +		]);
```js
[
	{ scheme: 'file', language: 'java' },
	{ scheme: 'jdt', language: 'java' },
	{ scheme: 'untitled', language: 'java' }
]
```

This can be a constant to be reuse.

2022-03-29 08:07 UTC, testforstephen commented on src/runtimeStatusBarProvider.ts
> +		]);
Support `pom.xml` and `.*\\.gradle(\\.kts)?$` as well.

2022-03-29 08:15 UTC, testforstephen commented on src/runtimeStatusBarProvider.ts
> +		this.buildFileStatusItem.command = {
I'd suggest to move the creations of all language status items to a factory class like "LanguageStatusFactory". And if you want to tune the styles and wording, you can do that in a central place.

2022-03-29 08:21 UTC, testforstephen commented
> ## when service is ready:
![image](https://user-images.githubusercontent.com/45906942/158581892-7e7c54e6-fb39-4369-8b99-26b054eac077.png)

"Show Server Status"  ->   "Show Build Status"

2022-03-30 06:35 UTC, CsCherrYY commented on src/runtimeStatusBarProvider.ts
> +		this.buildFileStatusItem.command = {
the refactoring and addressing of other comments have been included in https://github.com/redhat-developer/vscode-java/pull/2363/commits/7b2301a2001b2b2c8d1a331fcebf2645eb0bd823.

2022-03-30 07:41 UTC, testforstephen commented on src/serverStatusBarProvider.ts
> +		this.languageStatusItemAPI = (languages as any).createLanguageStatusItem;
No need set it as a private property. It can be a helper method for reuse. Also the vscode version in master branch is updated to 1.65, you can use languages.createLanguageStatusItem directly.

```typescript
function supportsLanguageStatus(): boolean {
	return !!languages.createLanguageStatusItem;
}
```

2022-03-30 07:44 UTC, testforstephen commented on src/languageStatusItemFactory.ts
> +export namespace LanguageStatusItemFactory {
=> ServerStatusItemFactory

2022-03-30 07:52 UTC, CsCherrYY commented on src/serverStatusBarProvider.ts
> +		this.languageStatusItemAPI = (languages as any).createLanguageStatusItem;
A helper method makes sense, but it seems the api is not available in Theia so we can't directly call it even we updated the vscode version.

![image](https://user-images.githubusercontent.com/45906942/160780288-b84a5029-1406-400d-ab15-d6ef896ff359.png)

2022-03-30 08:05 UTC, testforstephen commented on src/serverStatusBarProvider.ts
> +		this.languageStatusItemAPI = (languages as any).createLanguageStatusItem;
I don't ask you to use it directly. My point is that you don't need to store it to a variable `this.languageStatusItemAPI = (languages as any).createLanguageStatusItem;`.

Below is a sample usage.
```typescript
if (supportsLanguageStatus()) {
   languages.createLanguageStatusItem(...)
}
```

2022-03-30 08:11 UTC, CsCherrYY commented on src/serverStatusBarProvider.ts
> +		this.languageStatusItemAPI = (languages as any).createLanguageStatusItem;
get it.

2022-03-30 08:13 UTC, testforstephen commented on src/languageStatusItemFactory.ts
> +		tooltip: "Java language server is running in LightWeight mode, load projects to switch to Standard mode"
LightWeight mode provides limited features, please load projects to get full feature set.

2022-03-31 07:17 UTC, testforstephen commented on src/languageStatusItemFactory.ts
> +	return !vscode.languages.createLanguageStatusItem;
should be `!!vscode.languages.createLanguageStatusItem`

2022-03-31 07:25 UTC, testforstephen commented on src/languageStatusItemFactory.ts
> +		item.severity = (vscode as any).LanguageStatusSeverity?.Information;
Use `vscode.LanguageStatusSeverity` instead of `(vscode as any).LanguageStatusSeverity`.  Pls fix it in all occurrences.

2022-03-31 07:35 UTC, CsCherrYY commented on src/languageStatusItemFactory.ts
> +	return !vscode.languages.createLanguageStatusItem;
sorry for forgetting to add `!` back when testing the compatibility for old versions. I'll correct it later.

2022-04-02 11:14 UTC, testforstephen requested changes

2022-04-02 11:14 UTC, testforstephen commented on src/serverStatusBarProvider.ts
> +			this.showCleanItem();
Unless you can figure out the cases where "clean workspace" would help, I think it a bit confusing to show a "clean workspace" language status on project import failure.

2022-04-02 11:14 UTC, testforstephen commented on src/languageStatusItemFactory.ts
> +			title: "Show PROBLEMS panel",
-> Show PROBLEMS Panel

2022-04-02 11:14 UTC, testforstephen commented on src/languageStatusItemFactory.ts
> +		item.detail = "Project configuration error";
Project Configuration Error

2022-04-06 01:58 UTC, CsCherrYY commented on src/runtimeStatusBarProvider.ts
> +		const activeBuildTool: string | undefined = context.workspaceState.get(ACTIVE_BUILD_TOOL_STATE);
how about the following logics:

1. check `import.maven.enabled` and `import.gradle.enabled`
2. check `ACTIVE_BUILD_TOOL_STATE` if both of them are true. Otherwise, check the existence of enabled build tool file.

2022-04-06 02:17 UTC, testforstephen commented on src/runtimeStatusBarProvider.ts
> +		const activeBuildTool: string | undefined = context.workspaceState.get(ACTIVE_BUILD_TOOL_STATE);
Here is how to handle build conflict during importing stage.

https://github.com/redhat-developer/vscode-java/blob/e032c20f0e79b30285bf2568e812a67301e9f41c/src/extension.ts#L517-L550

2022-04-06 03:12 UTC, CsCherrYY commented on src/languageStatusItemFactory.ts
> +				tooltip: `Open config file`
👍, and we can directly use `vscode.workspace.asRelativePath()` to get the relative path.

2022-04-06 03:30 UTC, CsCherrYY commented on src/serverStatusBarProvider.ts
> +			this.showCleanItem();
Let's remove the clean item and keep eyes on it until we can specify the cases about "out of sync", which can be resolved by cleaning workspace.

2022-04-06 04:34 UTC, CsCherrYY commented on src/runtimeStatusBarProvider.ts
> +		const activeBuildTool: string | undefined = context.workspaceState.get(ACTIVE_BUILD_TOOL_STATE);
addressed in https://github.com/redhat-developer/vscode-java/pull/2363/commits/c4ff425e1ebb2741253a91bddf9b557beacc842b

2022-04-06 05:15 UTC, testforstephen commented on src/languageStatusItemFactory.ts
> +		arguments: ["Standard"],
-> `arguments: ["Standard", true]`

After I click `Load Projects`, it will pop up a dialog to ask if I want to switch to standard mode. This popup is not necessary to me. You can add an additional "true" to force it to start standard mode.

2022-04-06 05:40 UTC, CsCherrYY commented on src/languageStatusItemFactory.ts
> +		arguments: ["Standard"],
added in https://github.com/redhat-developer/vscode-java/pull/2363/commits/41e947d01b3d2c8d3c66f2ce45ec9add2ef8c8db

2022-04-06 05:58 UTC, testforstephen approved these changes
The latest changes look good to me.

2022-04-06 13:55 UTC, merged