Support publishing pre-release versions
redhat-developer/vscode-java pull request #2371
Opened 2022-03-22 02:31 UTC by CsCherrYY

fix #2285 

Notes:
- For the trigger part, I'm not sure the current trigger of Jenkins pipeline since it's on the Jenkins server, I suppose we trigger this pipeline after there is a commit to the vscode-java or eclipse.jdt.ls repository, so in this PR I add a trigger in the scripted pipeline to nightly build when there is SCM changes, if we can merge the  configuration with that in the current Jenkins server that would be fine.
- Due to the requirement of pre-release channel (see https://github.com/redhat-developer/vscode-java/issues/2285#issuecomment-1072075843), I have upgraded the engine in `package.json`. Besides, a tool node 14.x should be added to the Jenkins server (in this PR it's nodejs-14.19.1).
- Validation: for the pre-release versions, the packaged vsix file has an 'extension.manifest' file in its root path, and in that file, we can find 
> <Property` Id="Microsoft.VisualStudio.Code.PreRelease" Value="true" />

Signed-off-by: Shi Chen <chenshi@microsoft.com>

2022-03-22 06:47 UTC, CsCherrYY commented
test this please

2022-03-24 01:22 UTC, CsCherrYY commented
Sounds great. In this way, we will not make any SCM trigger change in this PR but it will happen on the server side, is that right? if so, I can remove this part then.

2022-03-30 10:04 UTC, CsCherrYY commented
@rgrunber I have removed the SCM trigger part in the Jenkins file.

For the node version and vsce version part, is there any gap in using node 14.x for publishing now?

2022-04-08 02:05 UTC, testforstephen commented on scripts/prepare-nightly-build.js
> +fs.writeFileSync("./package.insiders.json", JSON.stringify(insiderPackageJson));
Use `JSON.stringify(insiderPackageJson, null, 2)` to preserve the indentation.

2022-04-08 02:10 UTC, testforstephen commented on Jenkinsfile
> +	if (!publishToMarketPlace.equals('true')) {
In current Jenkinsfile, every commit will be published to stable or prerelease, which is not what we want.

I suggest adding a new build parameter like `publishPreRelease` to control whether we should package the vsix with `--pre-release` tag.

2022-04-08 02:33 UTC, CsCherrYY commented on Jenkinsfile
> +	if (!publishToMarketPlace.equals('true')) {
This approach (add a new parameter) makes sense, but I'm not sure if we can specify a parameter in the automatic trigger in Jenkins server. In other words, we should make the build of automatic trigger and manual trigger different parameters (`publishPreRelease`), to distinguish

- SCM trigger, with `publishPreRelease` == `true` and `publishToMarketPlace` == `true`
- manual CI, with `publishPreRelease`  == `false` and `publishToMarketPlace` == `false`
- manual release, with `publishPreRelease`  == `false` and `publishToMarketPlace` == `true`

2022-04-08 02:35 UTC, CsCherrYY commented on Jenkinsfile
> +	if (!publishToMarketPlace.equals('true')) {
BTW, if we can change the trigger strategy to daily build, like https://github.com/redhat-developer/vscode-java/pull/2371#issuecomment-1076509899, we will not publish a version on each commit, but on each day if new commit comes.

2022-04-08 02:38 UTC, testforstephen commented on Jenkinsfile
> +	if (!publishToMarketPlace.equals('true')) {
With this commit, current JBoss publish won't work any more. Are you planning to retire JBoss immediately?

2022-04-08 02:51 UTC, testforstephen commented on Jenkinsfile
> +	if (!publishToMarketPlace.equals('true')) {
> This approach (add a new parameter) makes sense, but I'm not sure if we can specify a parameter in the automatic trigger in Jenkins server. In other words, we should make the build of automatic trigger and manual trigger different parameters (`publishPreRelease`), to distinguish
> 
> * SCM trigger, with `publishPreRelease` == `true` and `publishToMarketPlace` == `true`
> * manual CI, with `publishPreRelease`  == `false` and `publishToMarketPlace` == `false`
> * manual release, with `publishPreRelease`  == `false` and `publishToMarketPlace` == `true`

This is not a technical issue. In Jenkins, there are many ways to pass variables, such as environment variables and build parameters.

2022-04-08 03:41 UTC, CsCherrYY commented on Jenkinsfile
> +	if (!publishToMarketPlace.equals('true')) {
get it, I'll keep the current build work and add a new build logic to publish a pre-release with a new environment variable.

2022-04-08 08:04 UTC, CsCherrYY commented
The newest commit I just separate the pre-release pipeline and keep the current builds work. All we should do in the Jenkins server are:

- Create a new pipeline, and target this repository
- Set the SCM trigger to daily build if new commit comes
- Copy the environment variables from the existing pipeline, without `publishToMarketPlace`. Instead, create a new variable `publishPreRelease` and set it to true.

2022-04-08 08:19 UTC, testforstephen commented on Jenkinsfile
> +		sh 'vsce publish -p ${TOKEN} --target win32-ia32 win32-arm64 linux-armhf alpine-x64 alpine-arm64'
When `vsce publish` command doesn't specify the vsix path, actually it will build a temp vsix from current src directory and then publish it to marketplace. This means this step will publish to the stable channel instead of pre-release.

2022-04-08 08:21 UTC, testforstephen commented on Jenkinsfile
> +		sh 'npx gulp clean_jre'
Originally this cleanup is used for publishing generic, because the generic publish step will repackage the vsix. It's not needed for platform vsix when using --packagePath in publish command.

2022-04-08 08:23 UTC, testforstephen commented on Jenkinsfile
> +		def platformVsixes = findFiles(glob: '**.vsix', excludes: vsix[0].path)
This will find all vsixes including the generic version so as to publish generic version twice.

2022-04-08 08:54 UTC, CsCherrYY commented on Jenkinsfile
> +		sh 'vsce publish -p ${TOKEN} --target win32-ia32 win32-arm64 linux-armhf alpine-x64 alpine-arm64'
Let's use `vsce publish --pre-release` here and skip the steps to package generic vsix when prerelease.

2022-04-08 09:00 UTC, CsCherrYY commented on Jenkinsfile
> +		sh 'npx gulp clean_jre'
Sure, Let's remove it.

2022-04-08 09:07 UTC, CsCherrYY commented on Jenkinsfile
> +	env.EXTENSION_VERSION = "${packageJson.version}"
used in `packageSpecificExtensions()`

2022-04-08 09:10 UTC, testforstephen commented on Jenkinsfile
> +		def platformVsixes = findFiles(glob: '**.vsix', excludes: vsix[0].path)
with the new logic, vsix[0].path doesn't exist any more, won't it report errors?

2022-04-08 09:14 UTC, CsCherrYY commented on Jenkinsfile
> +		def platformVsixes = findFiles(glob: '**.vsix', excludes: vsix[0].path)
Here I assign the variable in line 41 for the generic vsix file.
```
def vsix = findFiles(glob: '**.vsix')
```

2022-04-11 02:49 UTC, testforstephen approved these changes
LGTM

2022-04-11 02:54 UTC, testforstephen commented
@rgrunber there are two follow-ups for you:

- Install nodejs-14.19.1 in CI machine.
- Create a new pipeline for pre-release, see more details from @CsCherrYY comment above.

  > The newest commit I just separate the pre-release pipeline and keep the current builds work. All we should do in the Jenkins server are:
  > 
  > * Create a new pipeline, and target this repository
  > * Set the SCM trigger to daily build if new commit comes
  > * Copy the environment variables and credentials from the existing pipeline, without `publishToMarketPlace`. Instead, create a new variable `publishPreRelease` and set it to true.

2022-04-20 03:26 UTC, CsCherrYY commented
@rgrunber Could you please verify this change in the Jenkins server? If there is anything I can help, feel free to reach out🙂

2022-04-21 23:27 UTC, rgrunber requested changes
- The build seems to work as expected with `nodejs-14.19.1` :rocket: . I can confirm presence of `<Property Id="Microsoft.VisualStudio.Code.PreRelease" Value="true" />`
- I would also modify the `ovsx@<0.3.0` reference to just `ovsx` . Same situation as vsce ( https://github.com/eclipse/openvsx/commit/f5cc1a9e760039c18bf423b03b78ac620af56ae0 )
- I just need to create a PR on our end to add `publishPreRelease` (default `true`) as a parameter & to see how we can modify the job so it runs daily.

2022-04-21 23:27 UTC, rgrunber commented on scripts/prepare-nightly-build.js
> +const fs = require("fs");
I guess the script is fine for now. Initially I thought maybe you could use https://www.jenkins.io/doc/pipeline/steps/pipeline-utility-steps/#readjson-read-json-from-files-in-the-workspace , but with all the other manipulations it makes sense. Also, it's nice to run it locally.

I was thinking maybe it would be nice to have it in gulpfile.js so we have a common area for scripts (as opposed to gulpfile.js & scripts/ ) but this isn't the end of the world.

2022-04-22 06:27 UTC, CsCherrYY commented on Jenkinsfile
> +		}
Makes sense. Let's move this stage right after we extract server jars into server folder.

2022-04-22 06:44 UTC, CsCherrYY commented on Jenkinsfile
> +def publishPreReleaseExtensions() {
Yeah, here I just used a confused name. Let's divide the package step and the publish step into separate functions, in which the related variables like `publishPreRelease` or `publishToMarketPlace` are used.

2022-04-22 06:45 UTC, CsCherrYY commented on scripts/prepare-nightly-build.js
> +const fs = require("fs");
👍 Let's put it in `gulpfile.js`.

2022-05-11 21:21 UTC, rgrunber approved these changes
Just one minor thing to fix, but overall, works.

- I think you re-introduced the `"ovsx@<0.3.0"` line. Just make it `"ovsx"`. With node 14 we don't need to restrict it.

Just as a note, the Jenkins job has been configured to use an `scmpoll_spec` of `'0 8 * * *'` so it will build once per day only if there are new changes. We can play with this later if necessary.

2022-05-12 01:45 UTC, CsCherrYY commented
@rgrunber I have removed the version striction of ovsx. We can start to play with it!

2022-05-12 13:41 UTC, merged