Update language-client to 8.0.0-next.4
redhat-developer/vscode-java pull request #2377
Opened 2022-03-24 02:29 UTC by CsCherrYY

This PR is a part of #2376, to reduce the complexity of that PR. Type Hierarchy support has been introduced since language-client 8.0.0-next.4 so we should update this dependency, the language-client version requires vscode 1.61.0 for compiling, so I update this dependency as well.

- for notification part: see https://github.com/microsoft/vscode-languageserver-node#3170-next-protocol-800-next-json-rpc-800-next-client-and-800-next-server, now all `sendNotification` methods will return a promise.

2022-03-24 02:31 UTC, CsCherrYY commented on src/extension.ts
> -							client.logFailedRequest(CodeActionRequest.type, error);
I can't find this method in both the current version of language-client and 8.0.0 language-client. So there should be another fix?

2022-03-24 02:33 UTC, CsCherrYY commented on src/hoverAction.ts
> +            const serverHoverContentsMarkdown = [];
the type `MarkedString` and `MarkdownString` are incompatible now.

2022-03-24 02:37 UTC, CsCherrYY commented on src/extension.ts
> +									triggerKind: context.triggerKind,
`triggerKind` is a required field in VS Code now. Theia doesn't support this field now, see: https://eclipse-theia.github.io/vscode-theia-comparator/status.html but IMO this change will not introduce NPE since we just assign an undefined to a field.

2022-03-25 06:22 UTC, Eskibear commented on src/extension.ts
> -							client.logFailedRequest(CodeActionRequest.type, error);
I don't see method `logFailedRequest` in LanguageClient. 

It's introduced by https://github.com/redhat-developer/vscode-java/commit/78c82941606c1392f56b76491dc8aba87cd47faa , where client is of type 'any'. I'll invite @snjeza  to explain the details.

2022-03-25 06:22 UTC, Eskibear commented on src/extension.ts
> +									triggerKind: context.triggerKind,
This LGTM, should be no problem.

2022-03-25 06:35 UTC, Eskibear commented on src/hoverAction.ts
> +            const serverHoverContentsMarkdown = [];
FYI, `MarkedString` is deprecated in favor of `MarkdownString`. And `vscode.d.ts` changed. 

v1.53
```ts
export type MarkedString = MarkdownString | string | { language: string; value: string };
export class Hover {
		contents: MarkedString[];
```

v1.61
```ts
export type MarkedString = string | { language: string; value: string };
export class Hover {
		contents: Array<MarkdownString | MarkedString>;
```

2022-03-25 06:37 UTC, Eskibear commented on src/hoverAction.ts
> +            const serverHoverContentsMarkdown = [];
LGTM as long as we process it properly, making sure no regression in hover

2022-03-25 06:38 UTC, Eskibear commented on src/standardLanguageClient.ts
> +			context.subscriptions.push(commands.registerCommand(Commands.CONFIGURATION_UPDATE, async (uri) => projectConfigurationUpdate(this.languageClient, uri)));
what's the difference if we only prepend 'async' here without 'await'?

2022-03-25 06:47 UTC, CsCherrYY commented on src/standardLanguageClient.ts
> +			context.subscriptions.push(commands.registerCommand(Commands.CONFIGURATION_UPDATE, async (uri) => projectConfigurationUpdate(this.languageClient, uri)));
I think I miss the `await` here. The same to line 322.

2022-03-25 08:17 UTC, CsCherrYY commented on src/hoverAction.ts
> +            const serverHoverContentsMarkdown = [];
just checked again, and find hover in super implementation works.
![image](https://user-images.githubusercontent.com/45906942/160081649-7146babd-b2db-40d7-be9f-00664be98e1d.png)

2022-03-30 08:00 UTC, Eskibear approved these changes
LGTM.

2022-05-26 14:06 UTC, rgrunber commented
I ran into a problem updating to the language client to 8.0.1 in vscode-xml, and I suspect it'll be the same here. The extension will break on Theia.

Note: Node 14 needs to be used as with 12, I ran into `SyntaxError: Unexpected Token '?'`. (nullish coalescing issue).
Afterwards I ran into :

```
2022-05-26T13:34:36.203Z root INFO [hosted-plugin: 9987] PLUGIN_HOST(9987): PluginManagerExtImpl/loadPlugin(/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension)
2022-05-26T13:34:36.257Z root ERROR [hosted-plugin: 9987] Activating extension 'XML' failed: TypeError: Class extends value undefined is not a constructor or null
    at Object.1365 (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:447499)
    at n (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:655557)
    at Object.71 (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:340748)
    at n (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:655557)
    at Object.4384 (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:307797)
    at n (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:655557)
    at Object.2850 (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:481672)
    at n (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:655557)
    at Object.4060 (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:251645)
    at n (/home/rgrunber/.theia/extensions/vscode-xml-0.21.0.vsix/extension/dist/extension.js:2:655557)
```

`extension.js:2:447499` points to `class ProtocolTypeHierarchyItem extends code.TypeHierarchyItem`
`extension.js:2:251645` points to `const vscode_languageclient_1 = __webpack_require__(48);`

If I'm understanding how the `__webpack_require__` works, `const vscode_languageclient_1` is in `47`, which gets called at the very beginning by `const xmlExtensionApiImplementation_1 = __webpack_require__(47);` . This is from `xmlExtensionApiImplementation.ts` which originates in the vscode-xml sources.

So the act of referencing the language client causes TypeHierarchyItem to be referenced, which [Theia does not support](https://eclipse-theia.github.io/vscode-theia-comparator/status.html)

CC'ing @fbricon , @testforstephen in case I'm missing an obvious way to work around this.

2022-05-27 01:42 UTC, CsCherrYY commented
@rgrunber Yeah I had opened an issue here: https://github.com/eclipse-theia/theia/issues/10993, it seems Theia should support the related types (e.g., TypeHierarchyItem).

2022-10-25 13:37 UTC, rgrunber commented
We should re-investigate this soon. Once Theia releases, I'm hoping this will work. It seems they recently started supporting the Type Hierarchy API.

https://eclipse-theia.github.io/vscode-theia-comparator/status.html

2022-10-28 02:03 UTC, CsCherrYY commented
it seems that Theia has released a new version 1.31.0 which supports TypeHierarchyItem: https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md#breaking_changes_1.31.0

I will update the PR these days.

2022-10-28 14:16 UTC, rgrunber commented
I may have been a bit too optimistic. We will still need to wait for the end of the year to be able to make this change, but at least it will happen eventually :(

2022-10-31 01:53 UTC, CsCherrYY commented
@rgrunber is there anything I miss about this change? 

One concern is that we seem not to have a way to define the required Theia version in package.json, since only the newest Theia supports this API.

2023-01-30 08:42 UTC, CsCherrYY commented
https://github.com/redhat-developer/vscode-java/pull/2377/commits/3fba2fee58db1310dba9b8be3093c698bb38a20f updates the language client to newest 8.0.2. Comparing it with the former 8.0.0-next 4, the changes can be found also in https://github.com/microsoft/vscode-languageserver-node#3170-protocol-800-json-rpc-800-client-and-800-server:

- removeal of `onReady()`
- change of `ErrorHandler`

2023-02-06 21:24 UTC, datho7561 requested changes

2023-02-06 21:26 UTC, datho7561 commented
I tried this out, and I get an error notification when the syntax server is shut down. Is there a way to avoid this?

2023-02-07 07:26 UTC, CsCherrYY commented
> I tried this out, and I get an error notification when the syntax server is shut down. Is there a way to avoid this?

In the current version, when switching from syntax server to the standard server, we can also see these error messages in the syntax server output channel:
![image](https://user-images.githubusercontent.com/45906942/217176942-d22d7f87-29d0-4d29-96f0-a26590a93dc0.png)

And the behavior is introduced in https://github.com/microsoft/vscode-languageserver-node/issues/824, which forces the error message shown in the pop up. So I think the current way to solve this is to know why there is an error when syntax server stop.

2023-02-07 08:01 UTC, CsCherrYY commented
maybe https://github.com/eclipse/eclipse.jdt.ls/pull/1790 is related. @rgrunber could you provide any comments?

2023-02-07 08:05 UTC, CsCherrYY commented on package.json
> +    "vscode-languageclient": "^8.0.2",
Sounds great. added in https://github.com/redhat-developer/vscode-java/pull/2377/commits/c5afa6043ccdd3e51915a3c5a2ac4935ed30847b :)

2023-02-13 03:10 UTC, CsCherrYY commented
@datho7561 It seems that if we disable the client capability `shouldLanguageServerExitOnShutdown`, the error notification will not appear and the syntax server can shutdown successfully. Could you help verify it?

![image](https://user-images.githubusercontent.com/45906942/218361677-def39936-a68d-4773-9c4e-e443c7ea2cdb.png)

@rgrunber If it's true, I guess language client 8+ has fixed what we patch in https://github.com/eclipse/eclipse.jdt.ls/pull/1790.

2023-02-13 15:55 UTC, datho7561 commented
> ... if we disable the client capability `shouldLanguageServerExitOnShutdown`, the error notification will not appear and the syntax server can shutdown successfully

Yes, i think this is the right fix. This is what we did in https://github.com/redhat-developer/vscode-xml/commit/825823c6e7199052d338166d91dca13d434bf9a6 for vscode-xml

2023-02-13 16:30 UTC, datho7561 requested changes
After `shouldLanguageServerExitOnShutdown` is removed/set to false, I think this PR will be good

2023-02-13 16:30 UTC, datho7561 commented on src/providerDispatcher.ts
> +				return await languageClient.protocol2CodeConverter.asSymbolInformations(<clientSymbolInformation[]>symbolResponse);
If the result of the `protocol2CodeConverter` is a `Promise`, I think you should be able to return the `Promise` without using `await` and it will do the same thing. (this isn't a big deal though).

2023-02-16 06:06 UTC, jdneo commented
BTW, dose the new version of language client has native support of inlay hint? If yes, maybe we can remove https://github.com/redhat-developer/vscode-java/blob/master/src/inlayHintsProvider.ts and its related code.

2023-02-17 01:49 UTC, CsCherrYY commented
@jdneo I guess the anwser is yes. See: https://github.com/microsoft/vscode-languageserver-node#3170-protocol-800-json-rpc-800-client-and-800-server inlay hint support is in the list here. I also find the related types in the language-client library.

2023-02-17 01:51 UTC, CsCherrYY commented
it looks like `vscode-languageclient` version 8.1.0 is available, I'll take a look if we can directly update to this version.

2023-02-21 21:44 UTC, rgrunber reviewed
Overall, looks fine. I tried out rename, codelens, inlay hints, type hierarchy as those seem to be more at risk for breakage. It all seems to work well. The syntax server shuts down on its own as well.

I did noticed : https://github.com/redhat-developer/vscode-java/actions/runs/4200047119/jobs/7285652596#step:9:13 . The build still passes. Is this safe ?

2023-02-21 21:44 UTC, rgrunber commented on src/extension.ts
> +						shouldLanguageServerExitOnShutdown: false,
Yes, this was fixed in the language client release that supported 3.17. Original issue is at https://github.com/redhat-developer/vscode-java/issues/1928#issuecomment-832679999 . There's no need to set it to false as that's the default value anyways on the server side. In fact, there's a good argument for getting rid of it entirely since it was really to handle some non-protocol behaviour.

2023-02-22 02:22 UTC, Eskibear commented
> The build still passes. Is this safe ?

@rgrunber 
Probably we should upgrade version of typescript. See https://github.com/microsoft/TypeScript/issues/1778#issuecomment-913202933

2023-02-22 13:54 UTC, rgrunber commented
Ok, then let's go ahead and update typescript here if that will fix it.

2023-02-23 02:19 UTC, CsCherrYY commented on package.json
> -    "@types/node": "^8.10.51",
Since VS Code has switched to node 16 since 1.66 (https://code.visualstudio.com/updates/v1_66#_nodemoduleversion-and-nodejs-api-update), let's update this deps as well. The update will resolve the following error:
> node_modules/vscode-jsonrpc/lib/node/main.d.ts(8,37): error TS2307: Cannot find module 'worker_threads' or its corresponding type declarations.

2023-02-23 02:27 UTC, CsCherrYY commented
@rgrunber it looks like that issue got resolved after updating typescript and node :)

2023-02-23 04:00 UTC, merged