Smart Semicolon Detection issue with Swiss German Keyboard
redhat-developer/vscode-java pull request #3303
Opened 2023-09-15 19:41 UTC by snjeza

Fixes #3290

2023-09-29 20:04 UTC, rgrunber requested changes
Can you also confirm your PR restores the `;` behaviour for `java.format.onType` when smart semicolon detection is enabled ? I think this was a regression introduced by the original smart semicolon detection behaviour of overriding the `;` key. Now fixed with this PR.

![semicolon-on-type-formatting](https://github.com/redhat-developer/vscode-java/assets/1417342/df3a913b-1910-454f-bc88-36e0d988b283)

2023-09-29 22:04 UTC, snjeza commented on src/smartSemicolonDetection.ts
> +export async function smartSemicolonDetection() {
I have update the PR.
`handleTextDocumentchanges` is registered when the server is ready. See https://github.com/redhat-developer/vscode-java/pull/3303/commits/0d2a64e0478d8d7d6252f163c92ec8d8deb671c3#diff-d09bd91ab5c960ab619864434f60b35b363e614f20acb7ef19b898c7bec28ee7R152

2023-09-29 22:07 UTC, rgrunber commented on src/standardLanguageClient.ts
> +					context.subscriptions.push(workspace.onDidChangeTextDocument(event => handleTextDocumentChanges(event.document, event.contentChanges)));
The problem with moving it here under `ServiceReady` is the text block handling could still work prior to `ServiceReady`. Can't it be left where it was before in extension `activate()` but use `api.serverReady()` to confirm if we should perform the semicolon insertion logic ?

2023-09-29 22:30 UTC, snjeza commented on src/standardLanguageClient.ts
> +					context.subscriptions.push(workspace.onDidChangeTextDocument(event => handleTextDocumentChanges(event.document, event.contentChanges)));
Fixed.

2023-10-02 16:14 UTC, rgrunber reviewed
- I would also rename the commit message to something like "Re-implement smart semicolon detection through text document change API"

Looks good overall.

2023-10-02 16:33 UTC, snjeza commented on src/smartSemicolonDetection.ts
> +	if (!didSmartSemicolonInsertion() && enabled()) {
I have removed `didSmartSemicolonInsertion`.

2023-10-02 16:34 UTC, snjeza commented
> I would also rename the commit message to something like "Re-implement smart semicolon detection through text document change API"

I have updated the PR.

2023-10-02 17:49 UTC, rgrunber commented on src/smartSemicolonDetection.ts
>  import { commands, ExtensionContext, Position, Range, Selection, window } from 'vscode';
`ExtensionContext` can be removed.

2023-10-02 17:49 UTC, rgrunber commented on src/smartSemicolonDetection.ts
> +				setActive(true);
Is the purpose of `setActive` to prevent multiple text change events from entering this block and cause strange behaviour ? If so, would it make more sense to move `setActive` to just before the call to `executeCommand` ?

2023-10-02 17:49 UTC, rgrunber commented on src/smartSemicolonDetection.ts
> +				editBuilder.delete(new Range(new Position(oldPosition.line, oldPosition.character - 1), oldPosition));
Is it worth handling this case :

1. User inserts `;` at line 0 column 0 (eg. `|package org.foo`)
2. Immediately after inserting `;`, user hits the <kbd>left</kbd> arrow key moving the cursor from line 0, column 1, to line 0, column 0.

It seems if done quickly, this part of the code uses that updated cursor position.

```
rejected promise not handled within 1 second: Error: Illegal argument: character must be non-negative
extensionHostProcess.js:113
stack trace: Error: Illegal argument: character must be non-negative
	at $ (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:1101)
	at new n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:4382)
	at /home/rgrunber/git/vscode-java/dist/extension.js:102083:59
	at Object.edit (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:53232)
	at /home/rgrunber/git/vscode-java/dist/extension.js:102081:50
	at Generator.next (<anonymous>)
	at fulfilled (/home/rgrunber/git/vscode-java/dist/extension.js:102060:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

2023-10-02 19:44 UTC, snjeza commented on src/smartSemicolonDetection.ts
>  import { commands, ExtensionContext, Position, Range, Selection, window } from 'vscode';
Fixed.

2023-10-02 19:45 UTC, snjeza commented on src/smartSemicolonDetection.ts
> +				setActive(true);
Fixed

2023-10-02 19:49 UTC, snjeza commented on src/smartSemicolonDetection.ts
> +				editBuilder.delete(new Range(new Position(oldPosition.line, oldPosition.character - 1), oldPosition));
I can't reproduce the issue after moving `setActive`.

2023-10-02 20:51 UTC, rgrunber commented on src/smartSemicolonDetection.ts
> +				editBuilder.delete(new Range(new Position(oldPosition.line, oldPosition.character - 1), oldPosition));
I'm still able to reproduce but it's really a minor issue.

2023-10-02 20:53 UTC, merged